import bold from './bold';
import italic from './italic';
import underline from './underline';
import justifycenter from './justifycenter';
import justifyfull from './justifyfull';
import justifyleft from './justifyleft';
import justifyright from './justifyright';
import inserthorizontalrule from './inserthorizontalrule';
import image from './image';
import fontname from './fontname';
import fontsize from './fontsize';
import code from './code';
import full from './full';
import backcolor from './backcolor';
import forecolor from './forecolor';
import video from './video';
import table from './table';
import link from './link';
import cut from './cut';
import copy from './copy';
import paste from './paste';
import plainpaste from './plainpaste';
import wordpaste from './wordpaste';
import formatblock from './formatblock';
import redo from './redo';
import undo from './undo';
import indent from './indent';
import removeformat from './removeformat';
import insertunorderedlist from './insertunorderedlist';

const list = {};

list.bold = bold;
list.italic = italic;
list.underline = underline;
list.justifycenter = justifycenter;
list.justifyfull = justifyfull;
list.justifyleft = justifyleft;
list.justifyright = justifyright;
list.inserthorizontalrule = inserthorizontalrule;
list.image = image;
list.fontname = fontname;
list.fontsize = fontsize;
list.code = code;
list.full = full;
list.backcolor = backcolor;
list.forecolor = forecolor;
list.video = video;
list.table = table;
list.link = link;
list.cut = cut;
list.copy = copy;
list.paste = paste;
list.plainpaste = plainpaste;
list.wordpaste = wordpaste;
list.formatblock = formatblock;
list.redo = redo;
list.undo = undo;
list.indent = indent;
list.removeformat = removeformat;
list.insertunorderedlist = insertunorderedlist;

export default list;
