import bold from './bold';
import italic from './italic';
import underline from './underline';
import justifycenter from './justifycenter';
import justifyfull from './justifyfull';
import justifyleft from './justifyleft';
import justifyright from './justifyright';
import inserthorizontalrule from './inserthorizontalrule';
import image from './image';
import fontname from './fontname';
import fontsize from './fontsize';
import code from './code';
import full from './full';
import backcolor from './backcolor';
import forecolor from './forecolor';
import video from './video';
import table from './table';
import link from './link';
import cut from './cut';

const list = {};

list.bold = bold;
list.italic = italic;
list.underline = underline;
list.justifycenter = justifycenter;
list.justifyfull = justifyfull;
list.justifyleft = justifyleft;
list.justifyright = justifyright;
list.inserthorizontalrule = inserthorizontalrule;
list.image = image;
list.fontname = fontname;
list.fontsize = fontsize;
list.code = code;
list.full = full;
list.backcolor = backcolor;
list.forecolor = forecolor;
list.video = video;
list.table = table;
list.link = link;
list.cut = cut;

export default list;
